export const post = async (ev) => get(ev);

export const get = async () => {
  return {
    'subsonic-response': {
      status: 'ok',
      version: '1.16.0',
      album: {
        isDir: true,
        id: 'album-1',
        name: 'Moby Dick, or the Whale',
        title: 'Moby Dick, or the Whale',
        artistId: 'artist-1',
        artist: 'Herman Melville',
        created: '2021-05-01T10:00:00.000Z',
        songCount: 44,
        duration: 88670,
        song: [
          {
            isDir: false,
            isVideo: false,
            id: 1,
            name: 'Chapter 000: Etymology and Extracts',
            title: 'Chapter 000: Etymology and Extracts',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 1753,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_000_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 2,
            name: 'Chapter 001-002',
            title: 'Chapter 001-002',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 1436,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_001_002_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 3,
            name: 'Chapter 003',
            title: 'Chapter 003',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 2093,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_003_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 4,
            name: 'Chapter 004-007',
            title: 'Chapter 004-007',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 1630,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_004_007_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 5,
            name: 'Chapter 008-009',
            title: 'Chapter 008-009',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 1776,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_008_009_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 6,
            name: 'Chapter 010-012',
            title: 'Chapter 010-012',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 1168,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_010_012_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 7,
            name: 'Chapter 013-015',
            title: 'Chapter 013-015',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 1388,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_013_015_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 8,
            name: 'Chapter 016',
            title: 'Chapter 016',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 2118,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_016_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 9,
            name: 'Chapter 017-021',
            title: 'Chapter 017-021',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 2569,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_017_021_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 10,
            name: 'Chapter 022-025',
            title: 'Chapter 022-025',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 1645,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_022_025_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 11,
            name: 'Chapter 026-027',
            title: 'Chapter 026-027',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 1160,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_026_027_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 12,
            name: 'Chapter 028-031',
            title: 'Chapter 028-031',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 1500,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_028_031_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 13,
            name: 'Chapter 032',
            title: 'Chapter 032',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 2218,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_032_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 14,
            name: 'Chapter 033-035',
            title: 'Chapter 033-035',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 2291,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_033_035_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 15,
            name: 'Chapter 036-040',
            title: 'Chapter 036-040',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 2537,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_036_040_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 16,
            name: 'Chapter 041',
            title: 'Chapter 041',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 1589,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_041_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 17,
            name: 'Chapter 042-044',
            title: 'Chapter 042-044',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 2616,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_042_044_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 18,
            name: 'Chapter 045-047',
            title: 'Chapter 045-047',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 2229,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_045_047_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 19,
            name: 'Chapter 048-050',
            title: 'Chapter 048-050',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 2309,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_048_050_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 20,
            name: 'Chapter 051-053',
            title: 'Chapter 051-053',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 1625,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_051_053_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 21,
            name: 'Chapter 054',
            title: 'Chapter 054',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 3254,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_054_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 22,
            name: 'Chapter 055-058',
            title: 'Chapter 055-058',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 2229,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_055_058_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 23,
            name: 'Chapter 059-063',
            title: 'Chapter 059-063',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 2325,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_059_063_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 24,
            name: 'Chapter 064-067',
            title: 'Chapter 064-067',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 2225,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_064_067_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 25,
            name: 'Chapter 068-071',
            title: 'Chapter 068-071',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 2061,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_068_071_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 26,
            name: 'Chapter 072-073',
            title: 'Chapter 072-073',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 1474,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_072_073_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 27,
            name: 'Chapter 074-077',
            title: 'Chapter 074-077',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 1827,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_074_077_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 28,
            name: 'Chapter 078-080',
            title: 'Chapter 078-080',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 1443,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_078_080_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 29,
            name: 'Chapter 081-082',
            title: 'Chapter 081-082',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 2205,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_081_082_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 30,
            name: 'Chapter 083-086',
            title: 'Chapter 083-086',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 2258,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_083_086_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 31,
            name: 'Chapter 087-088',
            title: 'Chapter 087-088',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 2431,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_087_088_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 32,
            name: 'Chapter 089-091',
            title: 'Chapter 089-091',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 2036,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_089_091_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 33,
            name: 'Chapter 092-096',
            title: 'Chapter 092-096',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 2567,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_092_096_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 34,
            name: 'Chapter 097-100',
            title: 'Chapter 097-100',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 2605,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_097_100_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 35,
            name: 'Chapter 101-104',
            title: 'Chapter 101-104',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 2403,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_101_104_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 36,
            name: 'Chapter 105-108',
            title: 'Chapter 105-108',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 2227,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_105_108_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 37,
            name: 'Chapter 109-113',
            title: 'Chapter 109-113',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 2460,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_109_113_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 38,
            name: 'Chapter 114-118',
            title: 'Chapter 114-118',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 1557,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_114_118_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 39,
            name: 'Chapter 119-123',
            title: 'Chapter 119-123',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 1963,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_119_123_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 40,
            name: 'Chapter 124-127',
            title: 'Chapter 124-127',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 1960,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_124_127_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 41,
            name: 'Chapter 128-132',
            title: 'Chapter 128-132',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 2543,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_128_132_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 42,
            name: 'Chapter 133',
            title: 'Chapter 133',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 1498,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_133_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 43,
            name: 'Chapter 134',
            title: 'Chapter 134',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 1368,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_134_melville_64kb.mp3'
          },
          {
            isDir: false,
            isVideo: false,
            id: 44,
            name: 'Chapter 135 and Epilogue',
            title: 'Chapter 135 and Epilogue',
            artistId: 'artist-1',
            artist: 'Herman Melville',
            albumId: 'album-1',
            album: 'Moby Dick, or the Whale',
            created: '2021-05-01T10:00:00.000Z',
            duration: 2101,
            bitrate: 64,
            size: 1,
            suffix: 'mp3',
            contentType: 'audio/mpeg',
            stream:
              'https://archive.org/download/moby_dick_librivox/mobydick_135_melville_64kb.mp3'
          }
        ]
      }
    }
  };
};
