version: '3'

services:
  mesonic:
    container_name: mesonic
    build:
      context: .
      dockerfile: Dockerfile
    image: dbushell/mesonic
    restart: unless-stopped
    volumes:
      - ./config:/config
      - /Volumes/Audiobooks:/data:ro
      - ./server:/home/user/server
      - ./client:/home/user/client
    environment:
      - MESONIC_HOST=http://mesonic.localhost:4040
      - MESONIC_DEV=1
    ports:
      - 12080:12080
      - 4040:4040
